version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: gradle build
  
  test:
    docker:
      - image: circleci/openjdk:8-jdk
    working_directory: ~/repo
    steps:
      - checkout
      - run: gradle test

  deploy-qa:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/carbondemof-qa.git master

  deploy:
    docker:
      - image: buildpack-deps:trusty
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/carbondemof.git master
  
workflows:
  version: 2
  gotoprod:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy-qa:
          requires:
            - test
      - qa-approval:
          type: approval
          requires: 
            - deploy-qa
      - deploy:
          requires:
            - qa-approval